# Generated by Django 4.2.18 on 2025-01-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='year',
            field=models.CharField(default=2000, max_length=10),
            preserve_default=False,
        ),
    ]
