# Generated by Django 4.2.18 on 2025-01-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userportfolio_age_remove_userportfolio_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
